[build-system]
requires = [
  "scikit-build-core>=0.10",
  "torch==2.9.0",
  "wheel",
]
build-backend = "scikit_build_core.build"

[project]
<<<<<<< HEAD
name = "sglang-kernel-cpu"
=======
name = "sgl-kernel-cpu"
>>>>>>> v0.5.8
version = "0.3.21"
description = "Kernel Library for SGLang"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License"
]
dependencies = []

[project.urls]
"Homepage" = "https://github.com/sgl-project/sglang/tree/main/sgl-kernel"
"Bug Tracker" = "https://github.com/sgl-project/sglang/issues"

[tool.wheel]
exclude = [
  "dist*",
  "tests*",
]

[tool.scikit-build]
cmake.source-dir = "csrc/cpu"
cmake.build-type = "Release"
minimum-version = "build-system.requires"
wheel.packages = ["python/sgl_kernel"]
